// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtJahFISq-YEoVFTUqRfJ82bDD_soXCSE',
    appId: '1:830355642737:web:31dfd8846926ebf6c73ed0',
    messagingSenderId: '830355642737',
    projectId: 'final-project-7b51c',
    authDomain: 'final-project-7b51c.firebaseapp.com',
    storageBucket: 'final-project-7b51c.appspot.com',
    measurementId: 'G-K5659YBC2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEzC4q2eaQ1BibHjoWirOYFfrD8rb0I6k',
    appId: '1:830355642737:android:c444bea03fa94aa0c73ed0',
    messagingSenderId: '830355642737',
    projectId: 'final-project-7b51c',
    storageBucket: 'final-project-7b51c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DCbstAttECcHuO8d2RaFH3rX3qaCRBQ',
    appId: '1:830355642737:ios:39849635d255a0e9c73ed0',
    messagingSenderId: '830355642737',
    projectId: 'final-project-7b51c',
    storageBucket: 'final-project-7b51c.appspot.com',
    iosClientId: '830355642737-8tft3jqndlvhc0d8g42tdbpdtqtjrnor.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DCbstAttECcHuO8d2RaFH3rX3qaCRBQ',
    appId: '1:830355642737:ios:39849635d255a0e9c73ed0',
    messagingSenderId: '830355642737',
    projectId: 'final-project-7b51c',
    storageBucket: 'final-project-7b51c.appspot.com',
    iosClientId: '830355642737-8tft3jqndlvhc0d8g42tdbpdtqtjrnor.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectv2',
  );
}
